#!/usr/bin/env python3
"""
gen_alert_pcm.py — sound.py 합성 경고음을 UNO R4 DAC용 alert_pcm.h 로 렌더.

요점:
  · sound.py 를 그대로 import 해서 make_alert() 로 한 발(0.15s)을 합성한다.
  · SAMPLE_RATE 를 22050 으로 바꿔 '그 레이트에서 직접 합성' → 다운샘플 alias 없음.
  · 16-bit 정규화(_to_int16, 0.95 peak)를 거친 뒤 >>4 로 12-bit unsigned(0..4095,
    중앙 2048)로 매핑 → DAC analogWrite(12bit) 에 바로 들어갈 형식.

ANC 골짜기 톤(INSURANCE_HZ) 비중:
  insurance gain 을 올리면 옛 '듀오벨'처럼 저음 톤이 주역이 된다.
  주파수는 INSURANCE_HZ(=780, 옛 DuoBell 값. sound.py 기본은 750)로 둔다.
  - 0.3 : sound.py 기본(고역 스윕 주역, 저음 보험)
  - 0.9 : 듀오벨化(780Hz 를 주역급으로) ← 현재 값

재생성:  python3 gen_alert_pcm.py
사운드 경로 다르면:  SOUND_PY=/path/to/sound.py python3 gen_alert_pcm.py
"""
import os
import sys

import numpy as np

SOUND_PY = os.environ.get("SOUND_PY", "/Users/jangjunhyeok/python/sound.py")
OUT_H = os.path.join(os.path.dirname(os.path.abspath(__file__)), "alert_pcm.h")

DAC_RATE = 22050          # UNO R4 DAC ISR 재생 레이트
DURATION = 0.15           # 한 발 길이(s)
MODE = "normal"
INSURANCE_GAIN = 0.9      # ANC 골짜기 톤 비중 — 듀오벨化(주역급)
INSURANCE_HZ = 780        # ANC 골짜기 톤 주파수 — 옛 DuoBell 값(sound.py 기본은 750)
COLS = 12                 # .h 한 줄당 샘플 수

# sound.py 를 모듈로 로드
sys.path.insert(0, os.path.dirname(SOUND_PY))
import sound  # noqa: E402

# 22050Hz 에서 직접 합성 (functions 가 모듈 전역 SAMPLE_RATE 를 런타임에 참조)
sound.SAMPLE_RATE = DAC_RATE

# insurance 톤을 780Hz 로 (make_alert 가 insurance_low(duration) 를 모듈 전역 이름으로
# 호출하므로, 여기서 교체하면 make_alert 내부 호출이 이 버전을 쓴다)
_orig_insurance = sound.insurance_low
sound.insurance_low = (
    lambda duration=DURATION, f0=INSURANCE_HZ, decay=5.0:
    _orig_insurance(duration, f0, decay)
)

sig = sound.make_alert(duration=DURATION, mode=MODE,
                       gains=dict(insurance=INSURANCE_GAIN))

# sound.py 와 동일한 0.95-peak 정규화 → 16bit → 12bit unsigned(중앙 2048)
pcm16 = sound._to_int16(sig).astype(np.int32)     # -32768..32767, 0.95 peak
pcm12 = ((pcm16 + 32768) >> 4).clip(0, 4095)      # 0..4095, 0 → 2048(무음)

n = len(pcm12)
lines = [
    "#pragma once",
    "#include <Arduino.h>",
    f"// auto-generated by gen_alert_pcm.py from sound.py  "
    f"(mode={MODE}, {DURATION}s, 12bit DAC, insurance={INSURANCE_GAIN}@{INSURANCE_HZ}Hz 듀오벨化)",
    f"#define ALERT_RATE {DAC_RATE}",
    f"#define ALERT_LEN  {n}",
    "#define ALERT_MID  2048   // 무음(중앙값)",
    "const uint16_t ALERT_PCM[ALERT_LEN] PROGMEM = {",
]
for i in range(0, n, COLS):
    lines.append("  " + ",".join(str(int(v)) for v in pcm12[i:i + COLS]) + ",")
lines.append("};")

with open(OUT_H, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"wrote {OUT_H}: {n} samples @ {DAC_RATE}Hz, insurance={INSURANCE_GAIN}")
